import React, { useEffect, useState } from "react";
import {ScrollArea} from "@radix-ui/react-scroll-area";

export default function CourseList({onCourseClick}){
    const [courses, setCourses] = useState([]);
    useEffect(() => {
        fetch("http://localhost:8080/kalender/coursefeed")
            .then((response)=>response.json())
            .then((course)=> {
                setCourses(course);
                console.log(course);
            })
            .catch((error) => console.error("Errormessage", error))
    }, []);


    const jobTitleMap = {
        IN_STORE_TRAINER: 'In Store Trainer',
        IN_STORE_MERCHANDISE: 'In Store Merchandise',
        CONTACT_LENSE_CONSULTANT: 'Contact Lenses Consultant',
        OPTICAL_DISPENSER: 'Optical Dispenser',
        SALES_ASSISTANT: 'Sales Assistant',
        OPTICIAN: 'Optician',
        CL: 'CL',
        KD: 'KD',
        CLC: 'CLC',
        IST: 'IST',
        ISM: 'ISM',
        OD: 'OD',
    };


    // hardcoded - skal slettes mici - THIS IS GENERATED BY CHATGPT
    /*const coursesData = [
        {
            id: 1,
            title: 'Intro for nye elver',
            description: '3 dage i HQ',
            date: '2025-01-15',
            startTime: '10:00',
            endTime: '16:00',
            location: 'Aalborg',
            jobTitle: 'SALES_ASSISTANT',
        },
        {
            id: 2,
            title: 'Optiker Træning',
            description: 'Fokus på nye linseteknikker',
            date: '2025-02-20',
            startTime: '09:00',
            endTime: '14:00',
            location: 'Copenhagen',
            jobTitle: 'OPTICIAN',
        },
        {
            id: 3,
            title: 'Kundeservice Workshop',
            description: 'Forbedring af kundeservice færdigheder',
            date: '2025-03-05',
            startTime: '13:00',
            endTime: '17:00',
            location: 'Odense',
            jobTitle: 'SALES_ASSISTANT',
        },
        {
            id: 4,
            title: 'Linse Introduktion',
            description: 'Grundlæggende kontaktlinsepleje',
            date: '2025-04-10',
            startTime: '11:00',
            endTime: '15:00',
            location: 'Aarhus',
            jobTitle: 'CONTACT_LENSE_CONSULTANT',
        },
        {
            id: 5,
            title: 'Merchandising Strategier',
            description: 'Opstilling af produkter i butikken',
            date: '2025-05-22',
            startTime: '08:30',
            endTime: '12:30',
            location: 'Esbjerg',
            jobTitle: 'IN_STORE_MERCHANDISE',
        },
        {
            id: 6,
            title: 'Team Leadership Workshop',
            description: 'Træning i ledelsesfærdigheder for in-store trænere',
            date: '2025-06-18',
            startTime: '10:00',
            endTime: '17:00',
            location: 'Aalborg',
            jobTitle: 'IN_STORE_TRAINER',}
    ];*/


    return (
        <>
            <h1 className="text-4xl text-[#003811] font-bold mb-2 ml-4">Kursusliste</h1>
            <ScrollArea className="scrollbar-custom-courses flex flex-col h-[75vh] w-full rounded-xl p-4 overflow-y-auto">
                {courses.map((course, index) => (
                    <div  className="rounded-md w-full shadow-xl my-2 border border-[#003811] p-2 bg-white" key={course.id}
                          onClick={() => onCourseClick(course.date)}>

                        <h2 className="font-bold text-[#003811]">{course.title}</h2>
                        <p className="font-semibold text-gray-400 text-sm">{jobTitleMap[course.jobTitle]}</p>
                        <p className="flex items-center text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5m-9-6h.008v.008H12v-.008ZM12 15h.008v.008H12V15Zm0 2.25h.008v.008H12v-.008ZM9.75 15h.008v.008H9.75V15Zm0 2.25h.008v.008H9.75v-.008ZM7.5 15h.008v.008H7.5V15Zm0 2.25h.008v.008H7.5v-.008Zm6.75-4.5h.008v.008h-.008v-.008Zm0 2.25h.008v.008h-.008V15Zm0 2.25h.008v.008h-.008v-.008Zm2.25-4.5h.008v.008H16.5v-.008Zm0 2.25h.008v.008H16.5V15Z" />
                        </svg>
                            {course.date}  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-6 h-6 w-6 ml-10">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                            </svg>
                            {course.startTime} - {course.endTime} <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="size-6 h-6 w-6 ml-10">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1 1 15 0Z" />
                            </svg>
                            {course.location}</p>
                    </div>

                ))}
            </ScrollArea>
        </>
    );
}
